### PR TITLE
v3 branch setup

### PR DESCRIPTION
**Pull request by agouin**
This PR is into new branch: `v3`. Proposing that we maintain `v3` in addition to `main` until the majority of chains have migrated to `v5`.

Changes module path to `github.com/strangelove-ventures/ibctest/v3`. #284 changes the module path in main to `github.com/strangelove-ventures/ibctest/v5`. This will make the ibctest version in sync with ibc-go.

### CODE REVIEW

**Review by boojamya — APPROVED** [review]

**Comment by DavidNix** [comment]
What's the strategy for keep both main and v3 branches up to date? Or perhaps the v3 branch does not get many updates by design.

**Comment by agouin** [comment]
> What's the strategy for keep both main and v3 branches up to date?

With #285, PRs can be made against `main` if they are applicable to both v5 and v3. After the PR is merged into main, another PR will be made with a cherry-pick into `v3`

**Comment by DavidNix** [comment]
> > What's the strategy for keep both main and v3 branches up to date?
> 
> With #285, PRs can be made against `main` if they are applicable to both v5 and v3. After the PR is merged into main, another PR will be made with a cherry-pick into `v3`

Can we get another PR adding this info to the documentation? Probably under a "contributing" section.

**Comment by DavidNix** [comment]
@agouin Last question (I think): Does the `v3` branch run CICD similar to `main`?

**Comment by agouin** [comment]
> Can we get another PR adding this info to the documentation?

Yes, will add.

> Does the v3 branch run CICD similar to main?

Yes, I added the branch protection for `v3` to be the same requirements as `main`

**Review by DavidNix — APPROVED** [review]
Thanks for answering my questions!

**Pull request merged**
